### ISSUE TITLE
Won't play any video files

### ISSUE THREAD

**Issue by wagnerflo** [stax76/mpvnet#4]
Trying out your player I manage to get it to start. The right-click context menu shows up and I can click "Open Files" and choose a file. But then nothing happens. No error and the player window just stays black.

The same files play perfectly fine using mpv.exe from https://mpv.srsfckn.biz/

**Comment by stax76** [comment]
Does it fail with every type of file or only certain files?

**Comment by wagnerflo** [comment]
Only MKV files. Haven't had any other types readily available. Will download something and try later.

Is there some way to make the player log a bit?

**Comment by wagnerflo** [comment]
Sorry for getting back only now. I've tried the sample mp4 file from http://techslides.com/sample-webm-ogg-and-mp4-video-files-for-html5 and the problem persists. Seems to be independent of file format.

Interestingly audio-only files (I've tested a mp3) play fine...

**Comment by stax76** [comment]
Maybe it runs by changing video related settings, I use following on Win 10 with NVIDIA card:

hwdec=yes
vo=direct3d

https://mpv.io/manual/master/#video-output-drivers

**Comment by ilhamepri** [comment]
update soon?

**Comment by wagnerflo** [comment]
Yes. Setting "vo=direct3d" makes it work. Just strange that I need this explicitly in mpv.net but not mpv.exe...

**Comment by stax76** [comment]
> Just strange that I need this explicitly in mpv.net but not mpv.exe

it was set to opengl in mpv.net code along with a few other settings, it will be fixed in the next release, thanks for reporting and for the patience.

> update soon?

I hope I can upload a new build soon.
