### ISSUE TITLE
Is there a way to increase the font of the context menu (mpvnet)

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpvnet#5]
This is a question, not a bug. I tried to find a way to increase the right menu font size but i couldn't.

Is there a way to do it ?
Thanks

**Comment by stax76** [comment]
I made same change so you can do it with a new build:

https://github.com/stax76/mpvnet/releases

you have to create a script here:

C:\Users\frank\AppData\Roaming\mpv\scripts\font.cs

your code:

```
using System;
using System.Drawing;

using mpvnet;

class Script
{
    public Script()
    {
        var form = MainForm.Instance;
        form.Invoke(new Action(() => form.CMS.Font = new Font("Segoe UI", 12)));
    }
}
```

**Comment by 44vince44** [comment]
Thank you it has worked perfectly!!
